/**
* Represents an event generated by Game Engine
*/
export function GameEngineEvent(params){
	var originator;	// may be unit
	var battleOutcome;	// if any
	var eventType;	// UNIT_SELECTED, BATTLE_PERFORMED, UNIT_UPDATE, UNIT_DIE

	if (window === this){
		return new GameEngineEvent(params);
	}
	this._initialize(params);

	return this;
};

GameEngineEvent.prototype = {
	_initialize: function(params){
		this.originator = params.originator;
		this.battleOutcome = params.battleOutcome;
		this.eventType = params.eventType;
	},
};